From VM Thu Oct  4 15:25:26 2001
X-VM-v5-Data: ([nil nil nil nil nil nil nil nil nil]
	[nil "" "4" "November" "1999" "21:42:45" "-0000" "MAILER-DAEMON@gate0.n-h.net" "MAILER-DAEMON@gate0.n-h.net" nil "89" "failure notice" "^From:" nil nil "11" nil nil nil nil nil]
	nil)
Message-Id: <199911042119.QAA21584@python.org>
Content-Length: 3215
MIME-Version: 1.0
From: MAILER-DAEMON@gate0.n-h.net
To: psa-members-admin@python.org
Subject: failure notice
Date: 4 Nov 1999 21:42:45 -0000
X-Digest: Mailman bounce lack-of-detection

Hi. This is the qmail-send program at gate0.n-h.net.
I'm afraid I wasn't able to deliver your message to the following addresses.
This is a permanent error; I've given up. Sorry it didn't work out.

<psadisc@wwwmail.n-h.de>:

--- Below this line is a copy of the message.

Return-Path: <psa-members-admin@python.org>
Received: (qmail 23042 invoked from network); 4 Nov 1999 21:42:35 -0000
Received: from one.n-h.net (HELO n-h.net) (root@195.254.4.1)
  by wwwmail.n-h.de with SMTP; 4 Nov 1999 21:42:35 -0000
Received: from python.org (parrot.python.org [132.151.1.90])
	by n-h.net (8.8.5/8.8.5) with ESMTP id WAA00074
	for <psadisc@n-h.net>; Thu, 4 Nov 1999 22:45:15 +0100
Received: from python.org (localhost [127.0.0.1])
	by python.org (8.9.1a/8.9.1) with ESMTP id QAA20872;
	Thu, 4 Nov 1999 16:10:19 -0500 (EST)
Received: from origin.ea.com (hidden-user@gnat6.owo.com [208.12.170.6])
	by python.org (8.9.1a/8.9.1) with ESMTP id QAA20823
	for <psa-members@python.org>; Thu, 4 Nov 1999 16:09:48 -0500 (EST)
Received: from forest.origin.ea.com (molach.origin.ea.com [159.153.98.2])
	by origin.ea.com (8.8.8/8.8.8PJ) with ESMTP id PAA19774;
	Thu, 4 Nov 1999 15:26:35 -0600 (CST)
Received: by molach.origin.ea.com with Internet Mail Service (5.5.2448.0)
	id <VWGD5VQP>; Thu, 4 Nov 1999 15:00:30 -0600
Message-ID: <11A17AA2B9EAD111BCEA00A0C9B4179303385B62@molach.origin.ea.com>
From: "Asbahr, Jason" <Jasbahr@origin.EA.com>
To: "'beazley@cs.uchicago.edu'" <beazley@cs.uchicago.edu>, chriss@dnastar.com
Cc: psa-members@python.org
Subject: RE: [PSA MEMBERS] ObjC.py ?
Date: Thu, 4 Nov 1999 15:00:29 -0600 
MIME-Version: 1.0
X-Mailer: Internet Mail Service (5.5.2448.0)
Content-Type: text/plain;
	charset="iso-8859-1"
Sender: psa-members-admin@python.org
Errors-To: psa-members-admin@python.org
X-Mailman-Version: 1.0.2
Precedence: bulk
List-Id: Python Software Activity members discussion list <psa-members.python.org>
X-BeenThere: psa-members@python.org

I had the impression that SWIG supported the relatively recent
versions of GNU ObjC, but not earlier versions, such as NeXT's
original ObjC extensions to GCC.  True?

Cheers,

Jason Asbahr
Origin Systems, Inc.
jasbahr@origin.ea.com

-----Original Message-----
From: David Beazley [mailto:beazley@cs.uchicago.edu]
Sent: Wednesday, November 03, 1999 11:13 PM
To: chriss@dnastar.com
Cc: psa-members@python.org
Subject: Re: [PSA MEMBERS] ObjC.py ?


chriss@dnastar.com writes:
> Does anyone know what is left of the effort to interface
Python/ObjectiveC?
> E.g. is there a module, bits of code ... ?
> 

Well, it's not widely known, but SWIG has some support for ObjectiveC.
I haven't used this feature of SWIG in quite awhile, but I did use it
to build some Python interfaces to some simple ObjectiveC programs I
wrote about 3 years ago.  I can't think of any reason why it wouldn't
work (unless there has been some sort of bit-rot that I'm not aware
of).

Cheers,

Dave


_______________________________________________
PSA-members mailing list
PSA-members@python.org
http://www.python.org/mailman/listinfo/psa-members

_______________________________________________
PSA-members mailing list
PSA-members@python.org
http://www.python.org/mailman/listinfo/psa-members


